version: "3.8"

services:
  santiago:
    image: ghcr.io/santiagoalomoto/santiago7:latest
    build: .
    deploy:
      replicas: 1
      labels:
        - "traefik.enable=true"

        # Router HTTP
        - "traefik.http.routers.santiago.entrypoints=http"
        - "traefik.http.routers.santiago.rule=Host(`santiago.byronrm.com`)"

        # Redirección HTTP → HTTPS
        - "traefik.http.middlewares.santiago-https-redirect.redirectscheme.scheme=https"
        - "traefik.http.routers.santiago.middlewares=santiago-https-redirect"

        # Router HTTPS seguro
        - "traefik.http.routers.santiago-secure.entrypoints=https"
        - "traefik.http.routers.santiago-secure.rule=Host(`santiago.byronrm.com`)"
        - "traefik.http.routers.santiago-secure.tls=true"
        - "traefik.http.routers.santiago-secure.tls.certresolver=http"
        - "traefik.http.routers.santiago-secure.service=santiago"

        # Puerto interno del contenedor
        - "traefik.http.services.santiago.loadbalancer.server.port=80"

        # Red pública de traefik
        - "traefik.docker.network=traefik-public"
    networks:
      - traefik-public

networks:
  traefik-public:
    external: true
